version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=rssagg
    healthcheck:
      test: pg_isready -U root -d rssagg
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: pgadmin
    restart: always
    ports:
        - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    depends_on:
      postgres:
        condition: service_healthy
networks:
  default:
    name: psql-network
